### ISSUE TITLE
[Feature Request] Search comics including text

### ISSUE THREAD

**Issue by Pocketkid2** [mamaral/xkcd-Open-Source#53]
In the other XKCD app I have, I can search a phrase or text from the comic content itself, not just the title and it will find it. That would be awesome for this app! I even have an idea for how to do it.

**Comment by controversial** [comment]
"I even have an idea for how to do it" well what is that idea 😂

**Comment by mamaral** [comment]
Most of the comics come with a"transcript" value, and I was originally going to query that as well, but some of them are so generic you might get tons of results you don't want... I haven't tested it yet though so I'm not sure. Here's an example:

`"transcript": "[[A man with a beret and a woman are standing on a boardwalk, leaning on a handrail.]]\nMan: A woodpecker!\n<<Pop pop pop>>\nWoman: Yup.\n\n[[The woodpecker is banging its head against a tree.]]\nWoman: He hatched about this time last year.\n<<Pop pop pop pop>>\n\n[[The woman walks away.  The man is still standing at the handrail.]]\n\nMan: ... woodpecker?\nMan: It's your birthday!\n\nMan: Did you know?\n\nMan: Did... did nobody tell you?\n\n[[The man stands, looking.]]\n\n[[The man walks away.]]\n\n[[There is a tree.]]\n\n[[The man approaches the tree with a present in a box, tied up with ribbon.]]\n\n[[The man sets the present down at the base of the tree and looks up.]]\n\n[[The man walks away.]]\n\n[[The present is sitting at the bottom of the tree.]]\n\n[[The woodpecker looks down at the present.]]\n\n[[The woodpecker sits on the present.]]\n\n[[The woodpecker pulls on the ribbon tying the present closed.]]\n\n((full width panel))\n[[The woodpecker is flying, with an electric drill dangling from its feet, held by the cord.]]\n\n{{Title text: If you don't have an extension cord I can get that too.  Because we're friends!  Right?}}",`

**Comment by mamaral** [comment]
Closing this for now until we get a better idea what we can/want to do.

**Comment by Pocketkid2** [comment]
I'm not bothered about the ambiguity, this is more of an advanced feature that I use when I know exactly what I'm searching for. Specific phrases that are limited to one or just a few comics. Or even the name of the comic.

**Comment by mamaral** [comment]
I don't really understand what you mean. Can you elaborate?

**Comment by Pocketkid2** [comment]
Like if I know the name of a comic, or keywords in the title, I can type them it and it will start narrowing down. Maybe it downloads a list of all the titles and just searches that. A similar mechanic could apply for downloaded comics, where you could save the transcript of the comic with the image and search a collection of transcripts for keywords or phrases as you type them into the search bar. It's definately possible because I've seen it done in another app. Thanks for trying!

**Comment by mamaral** [comment]
What you're describing already exists in the app, that's why I'm confused. 

![](http://i.imgur.com/Q7805H2.jpg)

**Comment by kylehakala** [comment]
If I'm following correctly, this person would like to be able to search for the contents in the comic in your example of "Unpublished..." by searching for any of the words in the comic. 
E.g., that comic isn't the results page if I search for the word "discovery" despite that word being in the comic frame (which should then be in the transcript, yes?).

**Comment by mamaral** [comment]
Unless we did some OCR or something on all the comics, found a 3rd party API or similar that had all the content available to download and kept it up-to-date regularly, or manually transcribed them one-by-one, I don't see how I'd be able to search the actual content of the comic. I'd love suggestions though.

**Comment by kylehakala** [comment]
Can't the transcript be searched?

**Comment by mamaral** [comment]
Here's an example of what we get from the JSON api.

`{"month": "3", "num": 1805, "link": "", "year": "2017", "news": "", "safe_title": "Unpublished Discoveries", "transcript": "", "alt": "If you must know, I'm currently researching how to save this emailed tax form as a regular PDF so I can print and sign it. Our work isn't a lock for the Nobel, but we're in the running.", "img": "https://imgs.xkcd.com/comics/unpublished_discoveries.png", "title": "Unpublished Discoveries", "day": "1"}`

Many of the comics don't have transcripts, and the ones that do (you can see the third post in this thread) are not the text in the comic, they are descriptions of what is happening in the comic.

**Comment by kylehakala** [comment]
Ah... I think the only reasonable way to accomplish this would be to search the content of the xkcdexplains transcript section...

**Comment by Chris-McElroy** [comment]
Is there any chance this might get opened up again?  I agree that the explainxkcd is probably the best database to get the transcripts off to search with, that shouldn’t be too bad (I’d think).  Worst case, if we use the JSON api that was discussed, maybe it could be turned on and off in a setting?  I’d much prefer too many results than not enough.

I am very interested in helping making this happen, let me know if I can do anything to help!
